name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes
  $CHANGES

categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Breaking changes'
    labels:
      - 'breaking'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Housekeeping'
    labels:
      - 'housekeeping'

# autolabeler:
#   - label: 'feature'
#     branch:
#       - '/[Ff]eature.*/'
#       - '/[Ff]eat.*/'
#     title:
#       - '/[Ff]eature.*/'
#       - '/[Ff]eat.*/'
#   - label: 'bug'
#     branch:
#       - '/[Ff]ix.*/'
#       - '/[Hh]otfix.*/'
#       - '/[Bb]ugfix.*/'
#     title:
#       - '/[Ff]ix.*/'
#       - '/[Hh]otfix.*/'
#       - '/[Bb]ugfix.*/'
#   - label: 'documentation'
#     files:
#       - '*.md'
#     branch:
#       - '/[Dd]ocs.*/'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'
      - 'housekeeping'

exclude-labels:
  - 'skip-changelog'
